name = "MUMPS3"
uuid = "8158958c-316f-11e9-3ff7-338d4f1f622e"
authors = ["William R Sweeney <wrsweeney2@gmail.com>"]
version = "0.2.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
